### ISSUE TITLE
Package limitation not working

### ISSUE THREAD

**Issue by dkg** [Debian/dcs#98] opened 2019-11-04 17:12 UTC
I was looking for instances of the term "Reply-To" in the thunderbird codebase.

I put the search term:

      Reply-To package:\Qthunderbird\E

https://codesearch.debian.net/search?q=Reply-To+package%3A%5CQthunderbird%5CE&literal=1

but i get results from lots of different packages.

I tried the simpler search term:

     Reply-To package:thunderbird

https://codesearch.debian.net/search?q=Reply-To+package%3Athunderbird&literal=1

and i still get results from lots of different packages.

Both of these used to work for me, and the former URL is the kind that the per-package links suggest i should be using.

**Comment by dkg** [comment] 2019-11-04 17:20
ah, it seems to have to do with the "literal" dropdown choice.  if i switch that to "regex" then it works (and the `&literal=1` goes away from the URL).  it's pretty weird that the per-package links don't work though.

**Comment by stapelberg** [comment] 2019-11-22 07:57
Thanks for the report.

The issue is that we’re quoting the entire query (instead of just the search term, and not the extra keywords) when literal mode is selected:
https://github.com/Debian/dcs/blob/3baaecabca2d6c56799012c40c1245fc389cb6e6/static/instant.js#L78
https://github.com/Debian/dcs/blob/3baaecabca2d6c56799012c40c1245fc389cb6e6/cmd/dcs-web/serverrendered.go#L221

**Comment by stapelberg** [comment] 2019-11-22 08:31
Now fixed and deployed.

**Closed** 2019-11-22 08:31 UTC
